apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-portal
  template:
    metadata:
      labels:
        app: banking-portal
    spec:
      containers:
        - name: banking-portal
          image: banking-portal:0.0.1-dev
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: banking-portal-service
spec:
  selector:
    app: banking-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
